import Image from 'next/image';
import { Footer } from './footer';
import { Navbar } from './navbar';

const assets = {
  combo: 'https://static.where-e.com/Pakistan/Kebabish-Grill-Family-Restaurant-Bbq-Abdul-Hakim_66096a21d639790381a0c67f6b3468d0.jpg?class=mobile',
  menu: 'https://static.where-e.com/Pakistan/Kebabish-Grill-Family-Restaurant-Bbq-Abdul-Hakim_230f987e56289537bd217e4f0757347d.jpg',
  handi: 'https://static.where-e.com/Pakistan/Kebabish-Grill-Family-Restaurant-Bbq-Abdul-Hakim_195164c22db35b559694c7ed573c8eeb.jpg?class=mobile',
  biryani: 'https://static.where-e.com/Pakistan/Kebabish-Grill-Family-Restaurant-Bbq-Abdul-Hakim_6340257168c4b312b40c01d783451488.jpg?class=mobile',
  drinks: 'https://static.where-e.com/Pakistan/Kebabish-Grill-Family-Restaurant-Bbq-Abdul-Hakim_8413d10b57dc706a46e90eb5f9b7a024.jpg'
};
const foods = [
  ['BBQ & Tikka', 'The flame-grilled favourites made for sharing.', assets.combo],
  ['Karahi & Handi', 'Classic Pakistani recipes with deep, warming flavour.', assets.handi],
  ['Biryani', 'Aromatic rice, tender chicken and Kebabish spice.', assets.biryani],
  ['Drinks & Desserts', 'A refreshing finish to every family meal.', assets.drinks]
];
const features = [['01', 'Family Restaurant', 'A welcoming place for every generation.'], ['02', 'Fresh Food', 'Prepared with care for every order.'], ['03', 'BBQ & Pakistani Cuisine', 'Bold, familiar flavours from our kitchen.'], ['04', 'Marriage Hall', 'A venue designed for your celebrations.'], ['05', 'Quality Service', 'Warm hospitality from start to finish.']];
function Label({ children }: { children: React.ReactNode }) { return <p className="mb-5 flex items-center gap-3 text-[10px] font-semibold uppercase tracking-[.2em] text-saffron before:h-px before:w-8 before:bg-saffron">{children}</p>; }
function Action({ children, fill = true }: { children: React.ReactNode; fill?: boolean }) { return <a href="#contact" className={`inline-flex min-h-12 items-center gap-8 px-5 text-[10px] font-bold uppercase tracking-[.15em] transition hover:-translate-y-1 ${fill ? 'bg-saffron text-coal hover:bg-[#f0c362]' : 'border border-white/60 text-white hover:bg-white hover:text-coal'}`}>{children}<span>→</span></a>; }
export function HomePage() { return <><div className="grain"/><Navbar/><main>
<section id="home" className="relative flex min-h-[730px] items-center overflow-hidden bg-[#21120d] px-6 lg:px-14"><div className="absolute inset-0 opacity-45" style={{ background: 'radial-gradient(circle at 77% 47%, #c84320, transparent 16%), radial-gradient(circle at 82% 37%, #e9a245, transparent 7%), radial-gradient(circle at 78% 70%, #642116, transparent 20%), linear-gradient(110deg,#100d0b 20%,#4b1b13 70%,#120f0d)' }}/><div className="absolute right-[6%] top-1/2 hidden h-[530px] w-[390px] -translate-y-1/2 overflow-hidden rounded-t-full border border-saffron/40 bg-ember/30 shadow-2xl md:block"><Image src={assets.combo} alt="Kebabish Grill original menu artwork" fill className="object-cover opacity-90" sizes="390px" priority /></div><div className="relative z-10 max-w-[720px] pt-20"><Label>Family Restaurant & Marriage Hall · Abdul Hakim</Label><h1 className="display text-5xl leading-[.96] tracking-tight text-cream sm:text-7xl lg:text-[92px]">Authentic Taste.<br/><em className="font-normal text-saffron">Memorable Moments.</em></h1><p className="mt-7 max-w-lg text-sm leading-7 text-[#d6cbc1]">From signature BBQ and karahis to your family’s special celebrations, Kebabish Grill brings warmth, flavour and hospitality to every table.</p><div className="mt-8 flex flex-wrap gap-3"><Action>Explore Menu</Action><Action fill={false}>Book Now</Action></div></div><p className="absolute bottom-7 left-6 text-[10px] uppercase tracking-[.2em] text-[#c8b8a8] lg:left-14">Ghosia Chowk · Tulamba Road · Abdul Hakim</p></section>
<section id="about" className="grid gap-12 bg-[#1a1512] px-6 py-24 lg:grid-cols-2 lg:items-center lg:gap-24 lg:px-14 lg:py-36"><div className="relative mx-auto aspect-[4/5] w-full max-w-xl overflow-hidden border border-saffron/20"><Image src={assets.menu} alt="Original Kebabish Grill menu" fill className="object-cover" sizes="(max-width: 1024px) 100vw, 50vw"/><div className="absolute bottom-0 right-0 bg-saffron px-6 py-5 text-xs text-coal">Kebabish Grill<br/><strong className="display text-3xl">Family First</strong></div></div><div><Label>The Kebabish story</Label><h2 className="display text-4xl leading-tight sm:text-6xl">Good food brings<br/>people <em className="font-normal text-saffron">together.</em></h2><p className="mt-7 max-w-lg text-sm leading-7 text-[#b9aca0]">Kebabish Grill is built around the simple joy of sharing an authentic Pakistani meal. Our menu brings BBQ, tikka, karahi, handi and biryani together for easy family dining in Abdul Hakim.</p><a href="#contact" className="mt-8 inline-block text-[10px] font-bold uppercase tracking-[.18em] text-saffron">Discover Kebabish →</a></div></section>
<section id="menu" className="bg-coal px-6 py-24 lg:px-14 lg:py-36"><div className="mx-auto max-w-[1440px]"><Label>A taste for every occasion</Label><div className="mb-12 flex flex-col justify-between gap-6 md:flex-row md:items-end"><h2 className="display text-4xl sm:text-6xl">Our signature <em className="font-normal text-saffron">flavours.</em></h2><p className="max-w-xs text-sm leading-7 text-[#a99c90]">Kebabish favourites rooted in familiar Pakistani recipes and made for sharing.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{foods.map(([name, description, src]) => <article key={name} className="group relative h-[390px] overflow-hidden border border-white/10 bg-[#211812]"><Image src={src} alt={`${name} at Kebabish Grill`} fill className="object-cover transition duration-700 group-hover:scale-105" sizes="(max-width: 1280px) 50vw, 25vw"/><div className="image-shadow absolute inset-0"/><div className="absolute inset-x-6 bottom-6"><span className="text-[10px] tracking-[.2em] text-saffron">KEBABISH SPECIAL</span><h3 className="display mt-2 text-3xl">{name}</h3><p className="mt-1 text-xs text-[#e4d9cf]">{description}</p></div></article>)}</div></div></section>
<section id="hall" className="relative overflow-hidden bg-[#38110e] px-6 py-28 lg:px-14 lg:py-40"><div className="absolute inset-y-0 right-0 w-2/5 bg-[radial-gradient(circle_at_center,_#c56d38_0%,transparent_55%)] opacity-60"/><div className="relative max-w-2xl"><Label>Marriage Hall · Events · Celebrations</Label><h2 className="display text-5xl leading-tight sm:text-7xl">Your occasion,<br/><em className="font-normal text-saffron">our grand setting.</em></h2><p className="mt-7 max-w-xl text-sm leading-7 text-[#edd9c7]">From wedding functions to family occasions, let Kebabish Grill make your gathering feel special with a comfortable setting and generous hospitality.</p><div className="mt-8"><Action>Book Marriage Hall</Action></div></div><div className="absolute bottom-7 right-6 text-[10px] uppercase tracking-[.2em] text-[#ebc288] lg:right-14">Weddings · Receptions · Events</div></section>
<section id="gallery" className="bg-[#1a1512] px-6 py-24 lg:px-14 lg:py-36"><div className="mx-auto max-w-[1440px]"><div className="mb-12"><Label>Kebabish, in pictures</Label><h2 className="display text-4xl sm:text-6xl">From our kitchen to<br/><em className="font-normal text-saffron">your table.</em></h2></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{Object.entries(assets).map(([name, src], index) => <div className={`group relative overflow-hidden border border-white/10 ${index === 0 ? 'col-span-2 row-span-2 min-h-[420px]' : 'min-h-[200px]'}`} key={name}><Image src={src} alt={`Kebabish Grill ${name}`} fill className="object-cover transition duration-700 group-hover:scale-105" sizes="(max-width: 768px) 50vw, 25vw"/><div className="image-shadow absolute inset-0"/><span className="absolute bottom-4 left-4 capitalize text-sm text-white">{name} <b className="ml-1 text-saffron">↗</b></span></div>)}</div></div></section>
<section className="bg-coal px-6 py-24 text-center lg:px-14 lg:py-32"><Label>The Kebabish difference</Label><h2 className="display text-4xl sm:text-6xl">Feel welcome,<br/><em className="font-normal text-saffron">every time.</em></h2><div className="mx-auto mt-16 grid max-w-[1440px] border-t border-white/15 text-left sm:grid-cols-2 lg:grid-cols-5">{features.map(([number, title, description]) => <article className="min-h-56 border-b border-r border-white/15 p-6 last:border-r-0" key={number}><span className="text-[10px] tracking-[.18em] text-saffron">{number}</span><div className="mt-9 text-2xl text-saffron">✦</div><h3 className="display mt-5 text-xl">{title}</h3><p className="mt-3 text-xs leading-6 text-[#aa9c90]">{description}</p></article>)}</div></section>
<section id="contact" className="relative overflow-hidden bg-[#25100e] px-6 py-24 lg:px-14 lg:py-36"><div className="absolute right-0 top-0 h-full w-1/2 bg-[radial-gradient(circle_at_70%_55%,#7e2617_0%,transparent_55%)]"/><div className="relative mx-auto max-w-[1440px]"><div className="max-w-2xl border border-saffron/35 bg-coal/85 p-8 backdrop-blur sm:p-14"><Label>Find your table</Label><h2 className="display text-4xl sm:text-6xl">Come hungry.<br/><em className="font-normal text-saffron">Leave happy.</em></h2><div className="mt-9 divide-y divide-white/15 border-y border-white/15 text-sm"><a className="block py-4" href="tel:03337472104"><span className="block text-[9px] uppercase tracking-[.17em] text-[#a99c90]">Call us</span><strong className="mt-1 block text-cream">0333 7472104</strong></a><div className="py-4"><span className="block text-[9px] uppercase tracking-[.17em] text-[#a99c90]">Visit us</span><strong className="mt-1 block font-medium text-cream">Ghosia Chowk, Tulamba Road, Abdul Hakim</strong></div><div className="py-4"><span className="block text-[9px] uppercase tracking-[.17em] text-[#a99c90]">Opening hours</span><strong className="mt-1 block font-medium text-cream">9:00 AM – 1:00 AM</strong></div></div><div className="mt-7 flex flex-wrap gap-4"><Action>Book a Table</Action><a className="self-center text-[10px] font-bold uppercase tracking-[.15em] text-saffron" href="https://www.google.com/maps/search/?api=1&query=Kebabish+Grill+Family+Restaurant+%26+BBQ+Abdul+Hakim" target="_blank">Google Maps ↗</a></div></div></div></section>
</main><Footer/></>; }
